import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guide: [{type: 'autogenerated', dirName: 'guide'}],
  knowledge: [{type: 'autogenerated', dirName: 'knowledge'}],
  requirements: [{type: 'autogenerated', dirName: 'requirements'}],
  research: [{type: 'autogenerated', dirName: 'research'}],
  technical: [{type: 'autogenerated', dirName: 'technical'}],
};

export default sidebars;
